### PR TITLE
feat: Add firebaserc override and update readme

### PR DESCRIPTION
**Pull request by RobertGemmaJr**
The `.firebaserc` file is json so I updated it here. I could do `firebase.rules` as well but that's not a strictly json file?

Is there anything special I need to deploy the changes to npm?

### CODE REVIEW

**Review by broarr — APPROVED** [review]
This is great, thank you!

**Comment by broarr** [comment]
Do you know how to publish an npm package? I can show you!

**Comment by broarr** [comment]
I'd skip the rules file I think

**Comment by RobertGemmaJr** [comment]
> Do you know how to publish an npm package? I can show you!

Should I just do it locally from CJ? I did it a while back for `react-volume-viewer`

**Comment by broarr** [comment]
That works! You can also use CJ to add yourself to our NPM team and deploy as you from your machine. That's what I did

**Pull request merged**
